# Generated by Django 4.1.4 on 2023-01-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('psummary', models.CharField(max_length=300)),
                ('pcategory', models.CharField(choices=[('data', 'Data analysis'), ('coding', 'Coding'), ('writing', 'Writing'), ('creativity', 'DIY/Creative')], default='DIY/Creative', max_length=10)),
                ('purl', models.URLField(blank=True)),
                ('pstack', models.CharField(blank=True, choices=[('python', 'Python'), ('html', 'HTML'), ('cs', 'CSS'), ('java', 'Java'), ('c#', 'C#'), ('nodejs', 'NodeJS')], max_length=6)),
                ('pimage1', models.ImageField(blank=True, upload_to='projects/images/')),
                ('pimage2', models.ImageField(blank=True, upload_to='projects/images/')),
                ('pimage3', models.ImageField(blank=True, upload_to='projects/images/')),
            ],
        ),
    ]
