# Generated by Django 4.1.4 on 2023-01-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('data', 'Data analysis'), ('coding', 'Coding'), ('writing', 'Writing'), ('creativity', 'DIY/Creative')], default='DIY/Creative', max_length=10)),
                ('url', models.URLField(blank=True)),
                ('stack', models.CharField(blank=True, choices=[('python', 'Python'), ('html', 'HTML'), ('cs', 'CSS'), ('java', 'Java'), ('c#', 'C#'), ('nodejs', 'NodeJS')], max_length=6)),
                ('image1', models.ImageField(blank=True, upload_to='projects/images/')),
                ('image2', models.ImageField(blank=True, upload_to='projects/images/')),
                ('image3', models.ImageField(blank=True, upload_to='projects/images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
