# Generated by Django 4.1.4 on 2023-01-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_articles_delete_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='fulltext',
            field=models.TextField(default='Text me'),
        ),
    ]
