# Generated by Django 4.1.4 on 2023-01-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_articles_fulltext'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='image4',
            field=models.ImageField(blank=True, upload_to='projects/images/'),
        ),
        migrations.AddField(
            model_name='articles',
            name='image5',
            field=models.ImageField(blank=True, upload_to='projects/images/'),
        ),
    ]
