# Generated by Django 4.1.4 on 2023-01-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_articles_image4_articles_image5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='category',
            field=models.CharField(choices=[('Data Analysis', 'Data analysis'), ('Coding', 'Coding'), ('Writing', 'Writing'), ('Creativity', 'DIY/Creative')], default='DIY/Creative', max_length=15),
        ),
        migrations.AlterField(
            model_name='articles',
            name='stack',
            field=models.CharField(blank=True, choices=[('Python', 'Python'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('JAVA', 'Java'), ('C#', 'C#'), ('Nodejs', 'NodeJS')], max_length=10),
        ),
    ]
