# Generated by Django 4.1.4 on 2023-01-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_articles_category_alter_articles_stack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='stack',
            field=models.CharField(blank=True, choices=[('Python', 'Python'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('JAVA', 'Java'), ('C#', 'C#'), ('Nodejs', 'NodeJS'), ('SQL', 'SQL')], max_length=10),
        ),
    ]
