# Generated by Django 4.1.4 on 2023-02-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactname', models.CharField(max_length=40)),
                ('contactemail', models.EmailField(max_length=254)),
                ('contactsubject', models.CharField(max_length=50)),
                ('contactmessage', models.CharField(max_length=400)),
            ],
        ),
    ]
